### ISSUE TITLE
Restliche Popups erstellen

### ISSUE THREAD

**Issue by LukasFriesenecker** [MatthiasRiener/Slidea#58]
Popups:
- [x] add Image Drop
- [x] add Image Link
- [x] add Chart
- [x] add Quiz
- [x] add Quiz detail
- [x] visibility tasks

zu erledigen bis 05.01.2020

**Comment by MatthiasRiener** [comment]
Bitte schneller arbeiten - danke.

**Comment by MatthiasRiener** [comment]
![Uploading 103338371...]

**Comment by MatthiasRiener** [comment]
![image](https://user-images.githubusercontent.com/40741289/103338378-8608f200-4a7e-11eb-944d-b09a4750cd61.jpeg)
